security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_USER: IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN: ROLE_USER
        ROLE_MODERATOR: [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            anonymous: true
            
        main:
            pattern: ^/
            access_denied_url: /error403
            form_login:
                provider: fos_userbundle
                remember_me: true
                default_target_path: /target
            remember_me: 
                key: %secret%
            anonymous: true
            logout: true

    access_control:
        - { path: ^/admin, roles:  ROLE_ADMIN}    
        - { path: ^/moderate, roles:  ROLE_MODERATOR}       
        #- { path: ^/admin, roles:  ROLE_SUPER_ADMIN}
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
