parameters:
#    psa_user.example.class: Psa\UserBundle\Example

services:
#    psa_user.example:
#        class: %psa_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
