<?php

namespace Psa\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	
	public function search(EntityManager $em,$qsearch = null)
	{
		$sql   =  "SELECT a FROM PsaAdminBundle:Article a ";
		
		if($qsearch != null){
			$sql	.=	"WHERE a.titre LIKE '%$qsearch%' OR a.contenu LIKE '%$qsearch%'" ;
		}
		
		$sql .= "ORDER BY a.datePublication DESC";
		$query =  $em->createQuery($sql);
		$resultats = $query->getResult();
		return $resultats;
	}
	
}