<?php

namespace Psa\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageMetaRepository extends EntityRepository
{
}