PsaAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: PsaAdminBundle:Index:index }

PsaAdminBundle_about:
    pattern:  /about
    defaults: { _controller: PsaAdminBundle:About:index }

PsaAdminBundle_article:
    resource: "@PsaAdminBundle/Resources/config/routing/article.yml"
    prefix:   /article

PsaAdminBundle_document:
    resource: "@PsaAdminBundle/Resources/config/routing/document.yml"
    prefix:   /document

PsaAdminBundle_message:
    resource: "@PsaAdminBundle/Resources/config/routing/message.yml"
    prefix:   /message