parameters:
#    psa_admin.example.class: Psa\AdminBundle\Example

services:
#    psa_admin.example:
#        class: %psa_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
